services:
  

  booklibraryapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-api
    ports:
      - "5000:80"
    depends_on:
      - db
  
  booklibraryclient:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-client
    ports:
      - "5001:80"

  booklibraryapitests:
    build:
      context: .
      dockerfile: Dockerfile
      target: run-tests
    depends_on:
      - booklibraryapi

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: